version: '3.1'
services:
  database:
    image: mysql
    container_name: farmacia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farmacia_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
